<table width="505" border="0" cellspacing="0" cellpadding="0">
<tr>
    <td><img src="arquivos/imagens/biografia.jpg" width="505" height="41" /></td>
</tr>
<tr>
  <td width="505"><p align="justify">Marcelo Barbosa começou a tocar guitarra aos doze anos de idade.  Nestes primeiros passos, estudou com vários professores, mas foi  principalmente Allan Marshall quem lhe ensinou os princípios da  harmonia e improvisação.</p>
    <p align="justify">Tamanha dedicação deu  resultados precoces. Aos 17, já era músico profissional e lecionava em  duas grandes escolas de Brasília. Não demorou muito para que decidisse  encarar o desafio de montar a sua própria. Procurando diferenciar-se  das demais, seu foco foi montar um instituto especializado em guitarra,  coisa inédita na cidade. Empreendimento inovador, método idem. Ao invés  de copiar outros modelos existentes no mercado, Marcelo escreveu todo o  material didático da nova escola, e, além de dar aulas, também  coordenava os demais professores.</p>
    <p align="justify">Estávamos em  1996. Desenvolvendo-se ao longo de todo este tempo, atualmente o GTR é  uma das referências no ensino da guitarra no país e um dos mais  respeitados da América Latina. Atendeu a mais de quatro mil alunos e  conta com uma média de 600 matriculados regularmente em suas três  unidades na capital federal. Para comemorar sua primeira década de  existência, o GTR colocou no mercado um CD especial de 14 faixas com  alguns de seus mais notáveis nomes. Em geral, professores formados em  suas próprias dependências, ressaltando sua posição de revelador de  talentos. Lançado pelo selo brasiliense GRV, o álbum está disponível em  todo território nacional.</p>
    <p align="justify">Apesar de músico e  empresário de sucesso, Marcelo jamais se acomodou, estudando com  figuras de peso como Greg Howe (em duas oportunidades), Lula Galvão,  Hélio Delmiro, Toninho Horta, Guinga, Ian Guest, dentre outros,  aprimorando sua técnica e musicalidade. Em 2002, foi aos Estados Unidos  estudar na prestigiada Berklee College Of Music, a mais conceituada  faculdade de música do mundo. Nesta oportunidade, foi um dos doze  selecionados, dentre 400 concorrentes de todo o mundo, a receber uma  bolsa de estudos para o curso regular da faculdade. Assistiu também a  valiosos workshops, como o de Mike Stern. Aprofundou ainda mais seus  conhecimentos em guitarra jazz e harmonia, voltando ao Brasil para  retomar definitivamente os trabalhos com a banda Khallice, fundada por  ele em 1994 e já com dois EP’S no currículo.</p>
    <p align="justify">Após  inúmeros problemas e contratempos, Marcelo finalmente consegue colocar  o Khallice nos trilhos, rendendo “The Journey”, lançado em 2003. A  estréia do grupo foi recebida com enorme entusiasmo em todo o país.  Críticos especializados chegaram a considerá-los simplesmente como “a  melhor banda de prog metal do mundo”. O bom apoio originou diversos  shows, destacando-se a participação em grandes festivais, como “Porão  Do Rock”, “Brasília Music Festival”, “Brasil Metal Union” e “Forcaos”. </p>
    <p align="justify">2003  marcou também a sua estréia oficial em carreira solo. A coletânea  “Guitarras do Cerrado”, reunindo cinco dos mais expressivos nomes da  guitarra brasiliense, trouxe duas músicas inéditas instrumentais de  Marcelo, o que apenas ampliou os pedidos por workshops.</p>
    <p align="justify">Seu  prestígio, durante o tempo, abriu espaço para que recebesse o convite  para escrever em duas das mais conceituadas revistas especializadas em  guitarra do Brasil: Guitar Class, onde permaneceu por dois anos, e  Cover Guitarra, presente até hoje.</p>
    <p align="justify">Seguiram-se a  gravação do primeiro trabalho autoral de sua outra banda, a Zero 10.  Conhecida no cenário local e mais voltada ao pop e mpb, o lançamento  foi intitulado “Novo Dia” e é o espaço onde Marcelo permite-se explorar  suas várias facetas musicais numa banda, mostrando suas diversas  influências. </p>
    <p align="justify">Dando continuidade à sua carreira,  Marcelo foi convidado a escrever um método sobre técnica para a série  “Toque de Mestre” da editora HMP. Método este vendido com sucesso nas  bancas de todo o país. </p>
    <p align="justify">Veio então outra surpresa:  sua entrada no lendário trio de guitarras Tritone. Chamado para  substituir Frank Solari, Marcelo juntou-se a Sérgio Buss e Eduardo  Ardanuy, dois dos maiores guitarristas nacionais de todos os tempos,  para reativar o trio que lançou no final da década de noventa um  trabalho que se tornou um marco, “Just For Fun...And Maybe Some Money”.  Com entusiasmo, o trio prepara um novo álbum com cuidado e atenção. </p>
    <p align="justify">Duas  outras conquistas importantes sucederam-se. Primeiro, o lançamento,  pela Tagima, a principal marca nacional de instrumentos musicais, da  MB-1. A guitarra, moldada de acordo com as especificações de Marcelo,  integra o seleto time de “Signature Series” da empresa, acompanhando-o  no que quer que faça. Para completar, o Khallice assinou com a  gravadora estadunidense Magna Carta, considerada o maior e mais  importante selo mundial especializado em música progressiva. Disso  originou-se o relançamento de “The Journey” em todo mundo, com  embalagem e edição especial, além da parceria estender-se, no mínimo,  para os dois próximos álbuns da banda.</p>
    <p align="justify">De carreira  e projeção notáveis, Marcelo Barbosa atualmente é endorser da Tagima,  das cordas Elixir, dos cabos Santo Angelo e dos pedais NIG, todas  marcas referências de qualidade. Sempre com muito trabalho a realizar,  e firme em seus objetivos, Marcelo encontra-se em processo de  desenvolvimento do novo CD e do primeiro DVD do Khallice, de seu debut  completo na carreira solo e da retomada do Tritone, além de administrar  as três unidades do GTR e seguir fazendo shows e workshops pelo país.</p>
    <p align="justify">Como  lida com tantas atividades? “O prazer e dedicação de se fazer o que ama  supera todos os empecilhos, e é este o combustível que sempre me  impulsiona”, diz ele.<br />
      Firme, o nosso workaholic.</p>
    <p align="justify"><strong>Site Oficial:</strong> <a href="http://www.marcelobarbosa.com.br" target="_blank">www.marcelobarbosa.com.br</a><br />
        <strong>Khallice:</strong> <a href="http://www.khallice.com.br" target="_blank">www.khallice.com.br</a><br />
        <strong>Magna Carta:</strong> <a href="http://www.magnacarta.net" target="_blank">www.magnacarta.net</a><br />
        <strong>Zero 10:</strong> <a href="http://www.zero10.com.br" target="_blank">www.zero10.com.br</a><br />
        <strong>Tagima:</strong> <a href="http://www.tagima.com.br" target="_blank">www.tagima.com.br</a><br />
        <strong>Elixir:</strong> <a href="http://www.elixirstrings-americalatina.com" target="_blank">www.elixirstrings-americalatina.com</a><br />
        <strong>Santo Angelo:</strong> <a href="http://www.santoangelo.com.br" target="_blank">www.santoangelo.com.br</a><br />
        <strong>NIG:</strong> <a href="http://www.nigstrings.com.br" target="_blank">www.nigstrings.com.br</a></p>
    <p align="justify">Maurício Angelo - Assessoria de Imprensa<br />
        <br />
        <strong>Contato:</strong> +55 31 8778 25 11<br />
        <strong>Email:</strong> <a href="mailto:mgangelo@gmail.com">mgangelo@gmail.com</a></p>    </td>
</tr>

</table>
